services:
  api:
    build: ./api
    ports:
      - "3009:3009"
    volumes:
      - ./api:/api
      - api_node_modules:/api/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/frontend
      - frontend_node_modules:/frontend/node_modules

volumes:
  frontend_node_modules:
  api_node_modules:
